Even more changes to deal with the runtime library search path correctly on Solaris and others.

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -522,7 +522,7 @@ else
 fi
 
 
-# From configure.in Revision: 5.33 dnl
+# From configure.in Revision: 5.34 dnl
 
 # If `configure' is invoked (in)directly via `make', ensure that it
 # encounters no `make' conflicts.  Ignore error if shell does not have
@@ -624,43 +624,12 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Handle the --enable-shared option.
+# We need the real value of prefix and exec-prefix now, not when the generated
+# script is ready to output them.
 #------------------------------------------------------------------------------
 
-# Check whether --enable-shared or --disable-shared was given.
-if test "${enable_shared+set}" = set; then
-  enableval="$enable_shared"
-  BUILD_SHARED=$enableval
-else
-  BUILD_SHARED=NO
-fi
-
-case "$BUILD_SHARED" in
-    YES|yes)
-        echo "$ac_t""Will build shared libraries" 1>&6
-        BUILD_SHARED=YES
-        TCL_USE_SHLIB_CFLAGS=TCL_SHLIB_CFLAGS
-        TCLX_BUILD_LIB_SPEC="-L$bldbasedir/tcl/unix -ltclx"
-        TCLX_LIB_SPEC="-L$TCLX_LIB -ltclx"
-        TKX_BUILD_LIB_SPEC="-L$bldbasedir/tk/unix -ltkx"
-        TKX_LIB_SPEC="-L$TCLX_LIB -ltkx"
-        ;;
-    NO|no)
-        echo "$ac_t""Will not build shared libraries" 1>&6
-        BUILD_SHARED=NO
-        TCL_USE_SHLIB_CFLAGS=TCL_NO_SHLIB_CFLAGS  # Not actually defined
-        TCLX_BUILD_LIB_SPEC="$bldbasedir/tcl/unix/libtclx.a"
-        TCLX_LIB_SPEC="$TCLX_LIB/libtclx.a"
-        TKX_BUILD_LIB_SPEC="$bldbasedir/tk/unix/libtkx.a"
-        TKX_LIB_SPEC="$TCLX_LIB/libtkx.a"
-        ;;
-     *)
-        { echo "configure: error: Invalid argument to --enable-shared=" 1>&2; exit 1; }
-        ;;
-esac
-
-
-
+test "x$prefix" = xNONE && prefix=$ac_default_prefix
+test "x$exec_prefix" = xNONE && exec_prefix=$prefix
 
 
 
@@ -705,9 +674,12 @@ echo $ac_n "checking macro values from Config.mk""... $ac_c" 1>&6
 cat Config.mk >confmakefile
 echo "srcbasedir=$srcbasedir" >>confmakefile
 echo "bldbasedir=$bldbasedir" >>confmakefile
+echo "prefix=$prefix" >>confmakefile
+echo "exec_prefix=$exec_prefix" >>confmakefile
 echo "all:" >>confmakefile
 echo '	@echo TCL_CONFIG=\"${TCL_CONFIG}\"' >>confmakefile
 echo '	@echo TK_CONFIG=\"${TK_CONFIG}\"' >>confmakefile
+echo '	@echo TCLX_INST_LIB=\"${TCLX_INST_LIB}\"' >>confmakefile
 echo ".NO_PARALLEL: all" >>confmakefile
 
 eval `${MAKE-make} -f confmakefile`
@@ -723,10 +695,23 @@ if test "$TKX_BUILD" = "YES"; then
 fi
 echo "$ac_t""ok" 1>&6
 
+
+
 # Get defines from tclConfig.sh
 . $TCL_CONFIG
 
 LIBS=$TCL_LIBS   # Need for tests.
+
+#
+# Make TCL_LD_SEARCH_FLAGS a full value.  It is normally contains a value
+# with the path LIB_INSTALL_DIR.  Expand this to be the value of the 
+# TCL_EXEC_PREFIX.  Also, save the original search flags, we will need them
+# later.
+#
+ORIG_TCL_LD_SEARCH_FLAGS=$TCL_LD_SEARCH_FLAGS
+LIB_INSTALL_DIR=$TCL_EXEC_PREFIX
+TCL_LD_SEARCH_FLAGS=`eval echo $TCL_LD_SEARCH_FLAGS`
+
 
 
 
@@ -743,9 +728,54 @@ if test "$TKX_BUILD" = "YES"; then
    . $TK_CONFIG
 fi
 
+# Tk doesn't provide its own search flags, but should.
+TK_LD_SEARCH_FLAGS=$TCL_LD_SEARCH_FLAGS
 
 
 
+
+
+
+
+
+
+
+#------------------------------------------------------------------------------
+# Handle the --enable-shared option.  Must do this after extracting information
+# from Config.mk, as we need TCLX_INST_LIB.
+#------------------------------------------------------------------------------
+
+# Check whether --enable-shared or --disable-shared was given.
+if test "${enable_shared+set}" = set; then
+  enableval="$enable_shared"
+  BUILD_SHARED=$enableval
+else
+  BUILD_SHARED=NO
+fi
+
+case "$BUILD_SHARED" in
+    YES|yes)
+        echo "$ac_t""Will build shared libraries" 1>&6
+        BUILD_SHARED=YES
+        TCLX_USE_SHLIB_CFLAGS=TCL_SHLIB_CFLAGS
+        TCLX_BUILD_LIB_SPEC="-L$bldbasedir/tcl/unix -ltclx"
+        TCLX_LIB_SPEC="-L$TCLX_INST_LIB -ltclx"
+        TKX_BUILD_LIB_SPEC="-L$bldbasedir/tk/unix -ltkx"
+        TKX_LIB_SPEC="-L$TCLX_INST_LIB -ltkx"
+        ;;
+    NO|no)
+        echo "$ac_t""Will not build shared libraries" 1>&6
+        BUILD_SHARED=NO
+        TCLX_USE_SHLIB_CFLAGS=TCL_NO_SHLIB_CFLAGS  # Not actually defined
+        TCLX_BUILD_LIB_SPEC="$bldbasedir/tcl/unix/libtclx.a"
+        TCLX_LIB_SPEC="$TCLX_INST_LIB/libtclx.a"
+        TKX_BUILD_LIB_SPEC="$bldbasedir/tk/unix/libtkx.a"
+        TKX_LIB_SPEC="$TCLX_INST_LIB/libtkx.a"
+        ;;
+     *)
+        { echo "configure: error: Invalid argument to --enable-shared=" 1>&2; exit 1; }
+        ;;
+esac
 
 
 
@@ -830,14 +860,12 @@ esac
 
 
 #------------------------------------------------------------------------------
-# Determine the search path argument for the installed TclX libraries.  This
-# is hacked from the variable set in tclConfig.sh.
+# Determine the search path argument for the installed TclX libraries. 
 #-----------------------------------------------------------------------------
 
-TCLX_LD_SEARCH_FLAGS=`echo $TCL_LD_SEARCH_FLAGS|sed 's%/.*$%%'`
-
-if test "X$TCLX_LD_SEARCH_FLAGS" != "X"; then
-    TCLX_LD_SEARCH_FLAGS=$TCLX_LD_SEARCH_FLAGS$TCLX_INST_LIB
+if test "X$ORIG_TCL_LD_SEARCH_FLAGS" != "X"; then
+    LIB_INSTALL_DIR=$TCLX_INST_LIB
+    TCLX_LD_SEARCH_FLAGS=`eval echo $ORIG_TCL_LD_SEARCH_FLAGS` 
 fi
 
 
@@ -924,7 +952,7 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 928 "configure"
+#line 956 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -938,7 +966,7 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 942 "configure"
+#line 970 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -969,7 +997,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 973 "configure"
+#line 1001 "configure"
 #include "confdefs.h"
 #include <limits.h>
 EOF
@@ -1002,7 +1030,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1006 "configure"
+#line 1034 "configure"
 #include "confdefs.h"
 #include <sys/select.h>
 EOF
@@ -1043,7 +1071,7 @@ else
   ac_cv_c_cross=yes
 else
 cat > conftest.$ac_ext <<EOF
-#line 1047 "configure"
+#line 1075 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
@@ -1065,7 +1093,7 @@ if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1069 "configure"
+#line 1097 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -1087,7 +1115,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1091 "configure"
+#line 1119 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -1105,7 +1133,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1109 "configure"
+#line 1137 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -1126,7 +1154,7 @@ if test "$cross_compiling" = yes; then
   :
 else
 cat > conftest.$ac_ext <<EOF
-#line 1130 "configure"
+#line 1158 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -1161,7 +1189,7 @@ if eval "test \"`echo '$''{'ac_cv_type_clock_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1165 "configure"
+#line 1193 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1192,7 +1220,7 @@ if eval "test \"`echo '$''{'ac_cv_type_time_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1196 "configure"
+#line 1224 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1223,7 +1251,7 @@ if eval "test \"`echo '$''{'ac_cv_type_off_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1227 "configure"
+#line 1255 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1259,7 +1287,7 @@ if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1263 "configure"
+#line 1291 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1304,7 +1332,7 @@ if test "$cross_compiling" = yes; then
   { echo "configure: error: cross-compiling not supported" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1308 "configure"
+#line 1336 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -1390,7 +1418,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldnet_stub  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1394 "configure"
+#line 1422 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -1428,7 +1456,7 @@ if eval "test \"`echo '$''{'ac_cv_func_ftruncate'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1432 "configure"
+#line 1460 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char ftruncate(); below.  */
@@ -1477,7 +1505,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lx  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1481 "configure"
+#line 1509 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -1520,7 +1548,7 @@ if eval "test \"`echo '$''{'ac_cv_func_select'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1524 "configure"
+#line 1552 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char select(); below.  */
@@ -1568,7 +1596,7 @@ if eval "test \"`echo '$''{'ac_cv_func_setitimer'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1572 "configure"
+#line 1600 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char setitimer(); below.  */
@@ -1616,7 +1644,7 @@ if eval "test \"`echo '$''{'ac_cv_func_sigaction'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1620 "configure"
+#line 1648 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char sigaction(); below.  */
@@ -1664,7 +1692,7 @@ if eval "test \"`echo '$''{'ac_cv_func_setpgid'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1668 "configure"
+#line 1696 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char setpgid(); below.  */
@@ -1712,7 +1740,7 @@ if eval "test \"`echo '$''{'ac_cv_func_getgroups'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1716 "configure"
+#line 1744 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char getgroups(); below.  */
@@ -1760,7 +1788,7 @@ if eval "test \"`echo '$''{'ac_cv_func_bzero'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1764 "configure"
+#line 1792 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char bzero(); below.  */
@@ -1808,7 +1836,7 @@ if eval "test \"`echo '$''{'ac_cv_func_bcopy'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1812 "configure"
+#line 1840 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char bcopy(); below.  */
@@ -1856,7 +1884,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fsync'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1860 "configure"
+#line 1888 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fsync(); below.  */
@@ -1904,7 +1932,7 @@ if eval "test \"`echo '$''{'ac_cv_func_getpriority'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1908 "configure"
+#line 1936 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char getpriority(); below.  */
@@ -1952,7 +1980,7 @@ if eval "test \"`echo '$''{'ac_cv_func_strcoll'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1956 "configure"
+#line 1984 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char strcoll(); below.  */
@@ -2000,7 +2028,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fchown'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2004 "configure"
+#line 2032 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fchown(); below.  */
@@ -2048,7 +2076,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fchmod'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2052 "configure"
+#line 2080 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fchmod(); below.  */
@@ -2096,7 +2124,7 @@ if eval "test \"`echo '$''{'ac_cv_func_truncate'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2100 "configure"
+#line 2128 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char truncate(); below.  */
@@ -2144,7 +2172,7 @@ if eval "test \"`echo '$''{'ac_cv_func_waitpid'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2148 "configure"
+#line 2176 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char waitpid(); below.  */
@@ -2192,7 +2220,7 @@ if eval "test \"`echo '$''{'ac_cv_func_sysconf'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2196 "configure"
+#line 2224 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char sysconf(); below.  */
@@ -2245,7 +2273,7 @@ if eval "test \"`echo '$''{'ac_cv_func_inet_aton'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2249 "configure"
+#line 2277 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char inet_aton(); below.  */
@@ -2293,7 +2321,7 @@ if eval "test \"`echo '$''{'ac_cv_func_gethostname'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2297 "configure"
+#line 2325 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char gethostname(); below.  */
@@ -2347,7 +2375,7 @@ if eval "test \"`echo '$''{'ac_cv_func_catgets'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2351 "configure"
+#line 2379 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char catgets(); below.  */
@@ -2383,7 +2411,7 @@ if eval "test \"`echo '$ac_cv_func_'catgets`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   echo $ac_n "checking catclose return value""... $ac_c" 1>&6
      cat > conftest.$ac_ext <<EOF
-#line 2387 "configure"
+#line 2415 "configure"
 #include "confdefs.h"
 #include <nl_types.h>
 int main() { return 0; }
@@ -2424,7 +2452,7 @@ if eval "test \"`echo '$''{'ac_cv_func_random'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2428 "configure"
+#line 2456 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char random(); below.  */
@@ -2473,7 +2501,7 @@ if eval "test \"`echo '$''{'ac_cv_func_rename'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2477 "configure"
+#line 2505 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char rename(); below.  */
@@ -2523,7 +2551,7 @@ fi
 
 found_random=NO
 cat > conftest.$ac_ext <<EOF
-#line 2527 "configure"
+#line 2555 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -2535,7 +2563,7 @@ fi
 rm -f conftest*
 
 cat > conftest.$ac_ext <<EOF
-#line 2539 "configure"
+#line 2567 "configure"
 #include "confdefs.h"
 #include <math.h>
 EOF
@@ -2694,20 +2722,16 @@ s%@UNAME_OUT@%$UNAME_OUT%g
 s%@DATE_OUT@%$DATE_OUT%g
 s%@TKX_BUILD@%$TKX_BUILD%g
 s%@TCLX_ARCH@%$TCLX_ARCH%g
-s%@BUILD_SHARED@%$BUILD_SHARED%g
-s%@TCL_USE_SHLIB_CFLAGS@%$TCL_USE_SHLIB_CFLAGS%g
-s%@TCLX_BUILD_LIB_SPEC@%$TCLX_BUILD_LIB_SPEC%g
-s%@TCLX_LIB_SPEC@%$TCLX_LIB_SPEC%g
-s%@TKX_BUILD_LIB_SPEC@%$TKX_BUILD_LIB_SPEC%g
-s%@TKX_LIB_SPEC@%$TKX_LIB_SPEC%g
 s%@TCLX_VERSION@%$TCLX_VERSION%g
 s%@TCLX_FULL_VERSION@%$TCLX_FULL_VERSION%g
 s%@TCLX_SHLIB_VERSION@%$TCLX_SHLIB_VERSION%g
 s%@TKX_VERSION@%$TKX_VERSION%g
 s%@TKX_FULL_VERSION@%$TKX_FULL_VERSION%g
 s%@TKX_SHLIB_VERSION@%$TKX_SHLIB_VERSION%g
+s%@TCLX_INST_LIB@%$TCLX_INST_LIB%g
 s%@TCL_DEFS@%$TCL_DEFS%g
 s%@TCL_LIBS@%$TCL_LIBS%g
+s%@TCL_EXEC_PREFIX@%$TCL_EXEC_PREFIX%g
 s%@TCL_SHLIB_CFLAGS@%$TCL_SHLIB_CFLAGS%g
 s%@TCL_SHLIB_LD@%$TCL_SHLIB_LD%g
 s%@TCL_DL_LIBS@%$TCL_DL_LIBS%g
@@ -2717,11 +2741,18 @@ s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
 s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
 s%@TK_DEFS@%$TK_DEFS%g
 s%@TK_LIBS@%$TK_LIBS%g
+s%@TK_EXEC_PREFIX@%$TK_EXEC_PREFIX%g
 s%@TK_XINCLUDES@%$TK_XINCLUDES%g
 s%@TK_XLIBSW@%$TK_XLIBSW%g
 s%@TK_LD_SEARCH_FLAGS@%$TK_LD_SEARCH_FLAGS%g
 s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
 s%@TK_LIB_SPEC@%$TK_LIB_SPEC%g
+s%@BUILD_SHARED@%$BUILD_SHARED%g
+s%@TCLX_USE_SHLIB_CFLAGS@%$TCLX_USE_SHLIB_CFLAGS%g
+s%@TCLX_BUILD_LIB_SPEC@%$TCLX_BUILD_LIB_SPEC%g
+s%@TCLX_LIB_SPEC@%$TCLX_LIB_SPEC%g
+s%@TKX_BUILD_LIB_SPEC@%$TKX_BUILD_LIB_SPEC%g
+s%@TKX_LIB_SPEC@%$TKX_LIB_SPEC%g
 s%@CC@%$CC%g
 s%@RANLIB@%$RANLIB%g
 s%@TCLX_SHLIB_BASE_NAME@%$TCLX_SHLIB_BASE_NAME%g
