Fixed build problems with shared libraries on Solaris and HP-UX. Added *LIB_SPEC variables to tclx/tkxConfig.sh.

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -17,9 +17,9 @@ ac_help="$ac_help
   --with-arch=ARCH        architecture suffix, appended .ARCH to the bin
                       and lib directory names"
 ac_help="$ac_help
-  --enable-shared         build and link with shared libraries"
-ac_help="$ac_help
   --enable-master         enable master directory installation model"
+ac_help="$ac_help
+  --enable-shared         build and link with shared libraries"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -524,13 +524,23 @@ else
 fi
 
 
-# From configure.in Revision: 5.29 dnl
+# From configure.in Revision: 5.30 dnl
 
 # If `configure' is invoked (in)directly via `make', ensure that it
 # encounters no `make' conflicts.  Ignore error if shell does not have
 # unset.
 #
 unset MFLAGS MAKEFLAGS 2>/dev/null
+
+#------------------------------------------------------------------------------
+# Define srcbasedir and bldbasedir as absolute paths to the top of the TclX
+# tree.
+#------------------------------------------------------------------------------
+
+srcbasedir=`cd $srcdir/..; pwd`
+
+bldbasedir=`cd ..; pwd`
+
 
 #------------------------------------------------------------------------------
 # System information and date for including in some files.
@@ -616,42 +626,6 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Handle the --enable-shared option.
-#------------------------------------------------------------------------------
-
-# Check whether --enable-shared or --disable-shared was given.
-if test "${enable_shared+set}" = set; then
-  enableval="$enable_shared"
-  BUILD_SHARED=$enableval
-else
-  BUILD_SHARED=NO
-fi
-
-case "$BUILD_SHARED" in
-    YES|yes)
-        echo "$ac_t""Will build shared libraries" 1>&6
-        BUILD_SHARED=YES
-        TCL_USE_LIB=TCL_SHLIB
-        TCL_USE_SHLIB_CFLAGS=TCL_SHLIB_CFLAGS
-        TK_USE_LIB=TK_SHLIB
-        ;;
-    NO|no)
-        echo "$ac_t""Will not build shared libraries" 1>&6
-        BUILD_SHARED=NO
-        TCL_USE_LIB=TCL_LIB
-        TCL_USE_SHLIB_CFLAGS=TCL_NO_SHLIB_CFLAGS  # Not actually defined
-        TK_USE_LIB=TK_LIB
-        ;;
-     *)
-        { echo "configure: error: Invalid argument to --enable-shared=" 1>&2; exit 1; }
-        ;;
-esac
-
-
-
-
-
-#------------------------------------------------------------------------------
 # Handle the --enable-master option.
 #------------------------------------------------------------------------------
 
@@ -691,13 +665,45 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Define srcbasedir and bldbasedir as absolute paths to the top of the TclX
-# tree.
+# Handle the --enable-shared option.
 #------------------------------------------------------------------------------
 
-srcbasedir=`cd $srcdir/..; pwd`
+# Check whether --enable-shared or --disable-shared was given.
+if test "${enable_shared+set}" = set; then
+  enableval="$enable_shared"
+  BUILD_SHARED=$enableval
+else
+  BUILD_SHARED=NO
+fi
 
-bldbasedir=`cd ..; pwd`
+case "$BUILD_SHARED" in
+    YES|yes)
+        echo "$ac_t""Will build shared libraries" 1>&6
+        BUILD_SHARED=YES
+        TCL_USE_SHLIB_CFLAGS=TCL_SHLIB_CFLAGS
+        TCLX_BUILD_LIB_SPEC="-L$bldbasedir/tcl/unix -ltclx"
+        TCLX_LIB_SPEC="-L$TCLX_LIB -ltclx"
+        TKX_BUILD_LIB_SPEC="-L$bldbasedir/tk/unix -ltkx"
+        TKX_LIB_SPEC="-L$TCLX_LIB -ltkx"
+        ;;
+    NO|no)
+        echo "$ac_t""Will not build shared libraries" 1>&6
+        BUILD_SHARED=NO
+        TCL_USE_SHLIB_CFLAGS=TCL_NO_SHLIB_CFLAGS  # Not actually defined
+        TCLX_BUILD_LIB_SPEC="$bldbasedir/tcl/unix/libtclx.a"
+        TCLX_LIB_SPEC="$TCLX_LIB/libtclx.a"
+        TKX_BUILD_LIB_SPEC="$bldbasedir/tcl/unix/libtkx.a"
+        TKX_LIB_SPEC="$TCLX_LIB/libtkx.a"
+        ;;
+     *)
+        { echo "configure: error: Invalid argument to --enable-shared=" 1>&2; exit 1; }
+        ;;
+esac
+
+
+
+
+
 
 
 #------------------------------------------------------------------------------
@@ -787,6 +793,7 @@ fi
 
 
 
+
 #------------------------------------------------------------------------------
 # Check for various programs used during the build.  If the CC environment
 # variable is not set, the compiler used to build Tcl is used.
@@ -861,6 +868,18 @@ esac
 
 
 
+
+
+#------------------------------------------------------------------------------
+# Determine the search path argument for the installed TclX libraries.  This
+# is hacked from the variable set in tclConfig.sh.
+#-----------------------------------------------------------------------------
+
+TCLX_LD_SEARCH_FLAGS=`echo $TCL_LD_SEARCH_FLAGS|sed 's%/.*$%%'`
+
+if test "X$TCLX_LD_SEARCH_FLAGS" != "X"; then
+    TCLX_LD_SEARCH_FLAGS=$TCLX_LD_SEARCH_FLAGS$TCLX_INST_LIB
+fi
 
 
 #------------------------------------------------------------------------------
@@ -946,7 +965,7 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 950 "configure"
+#line 969 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -960,7 +979,7 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 964 "configure"
+#line 983 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -991,7 +1010,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 995 "configure"
+#line 1014 "configure"
 #include "confdefs.h"
 #include <limits.h>
 EOF
@@ -1024,7 +1043,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1028 "configure"
+#line 1047 "configure"
 #include "confdefs.h"
 #include <sys/select.h>
 EOF
@@ -1065,7 +1084,7 @@ else
   ac_cv_c_cross=yes
 else
 cat > conftest.$ac_ext <<EOF
-#line 1069 "configure"
+#line 1088 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
@@ -1087,7 +1106,7 @@ if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1091 "configure"
+#line 1110 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -1109,7 +1128,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1113 "configure"
+#line 1132 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -1127,7 +1146,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 1131 "configure"
+#line 1150 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -1148,7 +1167,7 @@ if test "$cross_compiling" = yes; then
   :
 else
 cat > conftest.$ac_ext <<EOF
-#line 1152 "configure"
+#line 1171 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -1183,7 +1202,7 @@ if eval "test \"`echo '$''{'ac_cv_type_clock_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1187 "configure"
+#line 1206 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1214,7 +1233,7 @@ if eval "test \"`echo '$''{'ac_cv_type_time_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1218 "configure"
+#line 1237 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1245,7 +1264,7 @@ if eval "test \"`echo '$''{'ac_cv_type_off_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1249 "configure"
+#line 1268 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1281,7 +1300,7 @@ if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1285 "configure"
+#line 1304 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1326,7 +1345,7 @@ if test "$cross_compiling" = yes; then
   { echo "configure: error: cross-compiling not supported" 1>&2; exit 1; }
 else
 cat > conftest.$ac_ext <<EOF
-#line 1330 "configure"
+#line 1349 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -1412,7 +1431,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldnet_stub  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1416 "configure"
+#line 1435 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -1450,7 +1469,7 @@ if eval "test \"`echo '$''{'ac_cv_func_ftruncate'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1454 "configure"
+#line 1473 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char ftruncate(); below.  */
@@ -1499,7 +1518,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lx  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1503 "configure"
+#line 1522 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -1542,7 +1561,7 @@ if eval "test \"`echo '$''{'ac_cv_func_select'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1546 "configure"
+#line 1565 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char select(); below.  */
@@ -1590,7 +1609,7 @@ if eval "test \"`echo '$''{'ac_cv_func_setitimer'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1594 "configure"
+#line 1613 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char setitimer(); below.  */
@@ -1638,7 +1657,7 @@ if eval "test \"`echo '$''{'ac_cv_func_sigaction'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1642 "configure"
+#line 1661 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char sigaction(); below.  */
@@ -1686,7 +1705,7 @@ if eval "test \"`echo '$''{'ac_cv_func_setpgid'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1690 "configure"
+#line 1709 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char setpgid(); below.  */
@@ -1734,7 +1753,7 @@ if eval "test \"`echo '$''{'ac_cv_func_getgroups'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1738 "configure"
+#line 1757 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char getgroups(); below.  */
@@ -1782,7 +1801,7 @@ if eval "test \"`echo '$''{'ac_cv_func_bzero'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1786 "configure"
+#line 1805 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char bzero(); below.  */
@@ -1830,7 +1849,7 @@ if eval "test \"`echo '$''{'ac_cv_func_bcopy'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1834 "configure"
+#line 1853 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char bcopy(); below.  */
@@ -1878,7 +1897,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fsync'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1882 "configure"
+#line 1901 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fsync(); below.  */
@@ -1926,7 +1945,7 @@ if eval "test \"`echo '$''{'ac_cv_func_getpriority'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1930 "configure"
+#line 1949 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char getpriority(); below.  */
@@ -1974,7 +1993,7 @@ if eval "test \"`echo '$''{'ac_cv_func_strcoll'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1978 "configure"
+#line 1997 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char strcoll(); below.  */
@@ -2022,7 +2041,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fchown'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2026 "configure"
+#line 2045 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fchown(); below.  */
@@ -2070,7 +2089,7 @@ if eval "test \"`echo '$''{'ac_cv_func_fchmod'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2074 "configure"
+#line 2093 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char fchmod(); below.  */
@@ -2118,7 +2137,7 @@ if eval "test \"`echo '$''{'ac_cv_func_truncate'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2122 "configure"
+#line 2141 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char truncate(); below.  */
@@ -2166,7 +2185,7 @@ if eval "test \"`echo '$''{'ac_cv_func_waitpid'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2170 "configure"
+#line 2189 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char waitpid(); below.  */
@@ -2214,7 +2233,7 @@ if eval "test \"`echo '$''{'ac_cv_func_sysconf'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2218 "configure"
+#line 2237 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char sysconf(); below.  */
@@ -2267,7 +2286,7 @@ if eval "test \"`echo '$''{'ac_cv_func_inet_aton'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2271 "configure"
+#line 2290 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char inet_aton(); below.  */
@@ -2315,7 +2334,7 @@ if eval "test \"`echo '$''{'ac_cv_func_gethostname'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2319 "configure"
+#line 2338 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char gethostname(); below.  */
@@ -2369,7 +2388,7 @@ if eval "test \"`echo '$''{'ac_cv_func_catgets'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2373 "configure"
+#line 2392 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char catgets(); below.  */
@@ -2405,7 +2424,7 @@ if eval "test \"`echo '$ac_cv_func_'catgets`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   echo $ac_n "checking catclose return value""... $ac_c" 1>&6
      cat > conftest.$ac_ext <<EOF
-#line 2409 "configure"
+#line 2428 "configure"
 #include "confdefs.h"
 #include <nl_types.h>
 int main() { return 0; }
@@ -2446,7 +2465,7 @@ if eval "test \"`echo '$''{'ac_cv_func_random'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2450 "configure"
+#line 2469 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char random(); below.  */
@@ -2495,7 +2514,7 @@ if eval "test \"`echo '$''{'ac_cv_func_rename'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2499 "configure"
+#line 2518 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char rename(); below.  */
@@ -2545,7 +2564,7 @@ fi
 
 found_random=NO
 cat > conftest.$ac_ext <<EOF
-#line 2549 "configure"
+#line 2568 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -2557,7 +2576,7 @@ fi
 rm -f conftest*
 
 cat > conftest.$ac_ext <<EOF
-#line 2561 "configure"
+#line 2580 "configure"
 #include "confdefs.h"
 #include <math.h>
 EOF
@@ -2713,14 +2732,12 @@ s%@includedir@%$includedir%g
 s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
+s%@srcbasedir@%$srcbasedir%g
+s%@bldbasedir@%$bldbasedir%g
 s%@UNAME_OUT@%$UNAME_OUT%g
 s%@DATE_OUT@%$DATE_OUT%g
 s%@TKX_BUILD@%$TKX_BUILD%g
 s%@TCLX_ARCH@%$TCLX_ARCH%g
-s%@BUILD_SHARED@%$BUILD_SHARED%g
-s%@TCL_USE_LIB@%$TCL_USE_LIB%g
-s%@TCL_USE_SHLIB_CFLAGS@%$TCL_USE_SHLIB_CFLAGS%g
-s%@TK_USE_LIB@%$TK_USE_LIB%g
 s%@TCLX_INST_BIN@%$TCLX_INST_BIN%g
 s%@TCLX_INST_LIB@%$TCLX_INST_LIB%g
 s%@TCLX_INST_INCL@%$TCLX_INST_INCL%g
@@ -2729,8 +2746,12 @@ s%@TKX_INST_BIN@%$TKX_INST_BIN%g
 s%@TKX_INST_LIB@%$TKX_INST_LIB%g
 s%@TKX_INST_INCL@%$TKX_INST_INCL%g
 s%@TKX_INST_MAN@%$TKX_INST_MAN%g
-s%@srcbasedir@%$srcbasedir%g
-s%@bldbasedir@%$bldbasedir%g
+s%@BUILD_SHARED@%$BUILD_SHARED%g
+s%@TCL_USE_SHLIB_CFLAGS@%$TCL_USE_SHLIB_CFLAGS%g
+s%@TCLX_BUILD_LIB_SPEC@%$TCLX_BUILD_LIB_SPEC%g
+s%@TCLX_LIB_SPEC@%$TCLX_LIB_SPEC%g
+s%@TKX_BUILD_LIB_SPEC@%$TKX_BUILD_LIB_SPEC%g
+s%@TKX_LIB_SPEC@%$TKX_LIB_SPEC%g
 s%@TCLX_VERSION@%$TCLX_VERSION%g
 s%@TCLX_FULL_VERSION@%$TCLX_FULL_VERSION%g
 s%@TCLX_SHLIB_VERSION@%$TCLX_SHLIB_VERSION%g
@@ -2740,16 +2761,17 @@ s%@TKX_SHLIB_VERSION@%$TKX_SHLIB_VERSION%g
 s%@TCL_DEFS@%$TCL_DEFS%g
 s%@TCL_LIBS@%$TCL_LIBS%g
 s%@TCL_SHLIB_CFLAGS@%$TCL_SHLIB_CFLAGS%g
+s%@TCL_SHLIB_LD@%$TCL_SHLIB_LD%g
 s%@TCL_DL_LIBS@%$TCL_DL_LIBS%g
 s%@TCL_LD_FLAGS@%$TCL_LD_FLAGS%g
-s%@TCL_SHLIB_LD@%$TCL_SHLIB_LD%g
-s%@SHLIB_LD@%$SHLIB_LD%g
+s%@TCL_LD_SEARCH_FLAGS@%$TCL_LD_SEARCH_FLAGS%g
 s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
 s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
 s%@TK_DEFS@%$TK_DEFS%g
 s%@TK_LIBS@%$TK_LIBS%g
 s%@TK_XINCLUDES@%$TK_XINCLUDES%g
 s%@TK_XLIBSW@%$TK_XLIBSW%g
+s%@TK_LD_SEARCH_FLAGS@%$TK_LD_SEARCH_FLAGS%g
 s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
 s%@TK_LIB_SPEC@%$TK_LIB_SPEC%g
 s%@CC@%$CC%g
@@ -2758,6 +2780,7 @@ s%@TCLX_SHLIB_BASE_NAME@%$TCLX_SHLIB_BASE_NAME%g
 s%@TCLX_SHLIB_NAME@%$TCLX_SHLIB_NAME%g
 s%@TKX_SHLIB_BASE_NAME@%$TKX_SHLIB_BASE_NAME%g
 s%@TKX_SHLIB_NAME@%$TKX_SHLIB_NAME%g
+s%@TCLX_LD_SEARCH_FLAGS@%$TCLX_LD_SEARCH_FLAGS%g
 s%@LN_S@%$LN_S%g
 s%@HAVE_SYML@%$HAVE_SYML%g
 s%@MAKEINCLUDE@%$MAKEINCLUDE%g
