Makes a change to the README file and the configuration process to make it possible to automatically patch tcl8.0b1.

diff --git a/unix/Makefile.in b/unix/Makefile.in
--- a/unix/Makefile.in
+++ b/unix/Makefile.in
@@ -13,7 +13,7 @@
 # software for any purpose.  It is provided "as is" without express or
 # implied warranty.
 #------------------------------------------------------------------------------
-# $Id: Makefile.in,v 8.0.4.1 1997/04/14 02:03:11 markd Exp $
+# $Id: Makefile.in,v 8.1 1997/04/17 05:00:18 markd Exp $
 #------------------------------------------------------------------------------
 #
 
@@ -146,6 +146,19 @@ TCLX_INSTALL_MAN:
 	${CPMANPAGES} -rmcat @${MAN_DIR_SEPARATOR}@ \
 	    ${TCLX_MAN_CMD_SECTION} ${TCLX_MAN_FUNC_SECTION} @@ \
 	    ${srcbasedir}/doc ${INSTALL_ROOT}${TCLX_INST_MAN}
+
+#------------------------------------------------------------------------------
+# Perform required patches to the Tcl core
+
+PATCH=patch
+patch-tcl-core:
+	@echo "Patching Tcl core in '${TCLSRC}' with required patches."
+	@cd ${TCL_SRC}; \
+	    for i in ${srcbasedir}/TCL-REQUIRED_PATCHES/*.patch ; \
+	    do \
+		echo patching $$i; \
+		${PATCH} --strip=0 --forward <$$i || echo PATCH FAILED, $i to ${TCL_SRC}; \
+	    done;
 
 #------------------------------------------------------------------------------
 # Clean up all files that were built by make.
